pom.xml
When using the actual snap in another project I get the following maven error:
> [INFO] Failed to resolve artifact.
> 
> Unable to get dependency information: Unable to read the metadata file for artifact 'net.schmizz:sshj:jar': Invalid JDK version in profile 'doclint-java8-disable': Unbounded range: [1.8, for project net.schmizz:sshj
>   net.schmizz:sshj:jar:0.10.1-SNAPSHOT
Fixed by bounding the version range.
=> Fixed unbounded range in pom.xml

README.adoc, src/main/java/net/schmizz/sshj/transport/KeyExchanger.java, src/main/java/net/schmizz/sshj/transport/mac/HMACSHA2256.java, src/main/java/net/schmizz/sshj/transport/mac/HMACSHA2512.java
These MACs where added in fdb891b842 but they didn't work for me after disabling md5&sha1. The server simply didn't respond anymore eventually resulting in a timeout. I debugged this and found two issues with the current code:
* both MACs have to use larger block/digest sizes, the previous values were the same that SHA1 had, but SHA2 needs 32 or 64 byte
* Additionally the KeyExchanger would only generate a 20 byte key when using diffie-hellman with sha1 as a KEX. For SHA2 larger keys are used, so the first message with a mac resulted in a "Corrupted MAC on input" error on the server. So the keys had to be resized like its already done for the Ciphers.
=> fixed block sizes for hmac-sha2-256 and hmac-sha2-512

src/main/java/net/schmizz/sshj/SocketClient.java
This is a simple PR to add java.net.Proxy support to SocketClient.  It's in "works for me" status, tested against a SOCKS proxy.
I'm not sure if you want the added repetition on the connect() methods or not.  I just followed the way things were already laid out.
This -might- resolve https://github.com/shikhar/sshj/issues/10 as well, but I don't have an available HTTP proxy to test.
=> Add proxy support for SocketClient/SSHClient

src/test/java/net/schmizz/sshj/transport/mac/BaseMacTest.java, src/test/java/net/schmizz/sshj/transport/mac/HMACMD596Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACMD5Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA196Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA1Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA2256Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA2512Test.java
As wished in #156 here are some unittests, for the HMACs at least. I'll try to look into creating a test for the KeyExchanger when I've got time.
While I was at it I created tests for all classes in the "mac"-package. This way I also found a bug in BaseMac which will be fixed with another PR (this is why some of the tests are currently disabled in HMACSHA196Test and HMACMD596Test).
The tests all create a hmac of "Hello World" with a random key of the expected size. I cross-checked the results with two different online services for hmacs.
=> added unit-tests for the "mac"-package

src/main/java/net/schmizz/sshj/transport/mac/BaseMAC.java, src/test/java/net/schmizz/sshj/transport/mac/BaseMacTest.java, src/test/java/net/schmizz/sshj/transport/mac/HMACMD596Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACMD5Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA196Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA1Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA2256Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA2512Test.java
The implementation of BaseMac would only take the bsize (size of the hash) into account if the #doFinal(byte[], int) method was called. Both other #doFinal methods would behave as if bsize==defbsize and not cut the hash to the right size.
This doesn't seem to be a problem right now because the #doFinal() seems to be entirely unused and #doFinal(byte[]) is only used by OpenSSHKnownHosts which always uses HMACSHA1 (with the default hash-size).
This PR depends on #164
=> Fix bsize bug

src/main/java/net/schmizz/sshj/transport/TransportImpl.java
OpenSSH will drop connections based on the value of `MaxStartups` when there are too many unauthenticated connection. When this happens, reads on the client socket return -1, which was previously inserted into the identification buffer, leading to the error in #118. This doesn't fix that issue, but hopefully makes it clear that it is a server problem, not a client problem.
=> Detect end-of-stream in TransportImpl#init

src/main/java/net/schmizz/sshj/sftp/RemoteFile.java
=> Fix length field for SSH_FXP_WRITE packets.

src/main/java/net/schmizz/sshj/transport/verification/OpenSSHKnownHosts.java, src/test/java/net/schmizz/sshj/transport/verification/OpenSSHKnownHostsTest.java
The SimpleEntry currently matches the hostname of the connection against
the complete hoststring of the entry. This way substrings also match, so
for example "10.0.0.1" matches on an entry for "10.0.0.10", resulting in
a host-key-changed message if the key differs which is usually does.
=> bugfix: match complete host instead of contains on the hoststring

src/main/java/net/schmizz/sshj/sftp/RemoteFile.java
=> fix for issue 183 (buffer overrun in sftp.RemoteFile.ReadAheadRemoteFileInputStream)

build.gradle, src/main/java/net/schmizz/sshj/xfer/scp/AbstractSCPClient.java, src/main/java/net/schmizz/sshj/xfer/scp/SCPDownloadClient.java, src/main/java/net/schmizz/sshj/xfer/scp/SCPEngine.java, src/main/java/net/schmizz/sshj/xfer/scp/SCPFileTransfer.java, src/main/java/net/schmizz/sshj/xfer/scp/SCPUploadClient.java, src/test/java/net/schmizz/sshj/xfer/scp/SCPFileTransferTest.java
Hello,
I have a strong requirement to limit usage of bandwidth at application level when I upload files to a remote server. 
According to the scp man page, I have added a '-l XXX' arg to the SCPEngine class.
Then, to keep the fluent aspect of your API, this new arg can (optionally) be set as below:
```java
// Limit upload transfert at 128Ko/s
ssh.newSCPFileTransfer().bandwidthLimit(1024).upload(new FileSystemFile(src), "/tmp/");
```
A test case is provided into SCPFileTransferTest for upload and download features.
Thanks.
=> SCP : limit the used bandwidth

src/main/java/net/schmizz/sshj/SSHClient.java, src/main/java/net/schmizz/sshj/SocketClient.java, src/main/java/net/schmizz/sshj/connection/channel/direct/LocalPortForwarder.java
In the spirit of keeping PRs functionally-targeted, submitted for your approval are a few changes pertaining to working with SSH gateways and proxies.
First, I re-ordered the connect methods in SocketClient.java, so that all the String-based and InetAddress-based methods would be grouped together (so that I wouldn't have to jump around in the file when working on them).  Then, I eliminated all use of InetAddress.getByName in the String-based connect methods, because when you're connecting through a gateway or Proxy you may not actually have the ability to resolve the DNS name of the target host (but the Proxy or gateway will).
I also added some lightweight management of LocalPortForwarders to the SSHClient class, because when the client is closed, I want any LocalPortForwarders that are …
=> Modifications for working with SSH gateways

src/main/java/net/schmizz/sshj/SSHClient.java, src/main/java/net/schmizz/sshj/connection/channel/AbstractChannel.java, src/main/java/net/schmizz/sshj/connection/channel/Channel.java, src/main/java/net/schmizz/sshj/sftp/FileMode.java, src/main/java/net/schmizz/sshj/sftp/Response.java, src/main/java/net/schmizz/sshj/sftp/SFTPClient.java, src/main/java/net/schmizz/sshj/sftp/SFTPFileTransfer.java
These are the remaining changes I had to add to sshj for compatibility with Joval's jSAF provider code.  They're all relatively minor so I hope it makes sense to group them together:
1) Re-wrote try-with-resources and inferred generics constructors (no functional changes) so that the project can be built using Java 6.
2) Added a method to the Channel interface to make it possible to determine whether an EOF has been received.
3) Added some missing SFTP response codes.
5) Fixed a typo in an SFTP enum.
=> Compatibility features

src/main/java/net/schmizz/sshj/common/Buffer.java, src/main/java/net/schmizz/sshj/common/KeyType.java, src/main/java/net/schmizz/sshj/transport/verification/OpenSSHKnownHosts.java, src/main/java/net/schmizz/sshj/userauth/keyprovider/PKCS5KeyFile.java
If BouncyCastle is not present, I want to be able to load whatever bits of the known_hosts file I can (i.e., the ssh-dss and ssh-rsa keys).
While making this change I noticed the KeyType.readPubKeyFromBuffer method didn't require passing in the String type name, so I cleaned that up too.
=> Gracefully load OpenSSH known_hosts without requiring BouncyCastle

src/main/java/net/schmizz/keepalive/KeepAlive.java
Interrupt signal may be catched when keepalive thread is sleeping. It will still go into conn.getTransport().die(e) when we called keepalive.interrupt().
=> Catch interrupt signal in keepalive thread

src/main/java/net/schmizz/sshj/DefaultConfig.java, src/main/java/net/schmizz/sshj/common/SSHRuntimeException.java
1) We shouldn't assume that the current thread context ClassLoader has access to the sshj.properties file, but it's safe to assume that the DefaultConfig class's ClassLoader does.
2) When creating an SSHRuntimeException based on a Throwable, I believe the SSHRuntimeException should adopt the message of the Throwable cause (instead of always using null).
WDYT?
=> Two minor changes

build.gradle
This completes the work to correct bug #255.
The dependency was removed from the code, but the MANIFEST.MF file still had a reference to the private package.
=> excludes net.i2p.crypto.eddsa.math from OSGI Import-Package

src/main/java/com/hierynomus/sshj/backport/Jdk7HttpProxySocket.java, src/main/java/net/schmizz/sshj/SSHClient.java, src/main/java/net/schmizz/sshj/common/Buffer.java, src/main/java/net/schmizz/sshj/connection/channel/AbstractChannel.java, src/main/java/net/schmizz/sshj/connection/channel/Channel.java, src/main/java/net/schmizz/sshj/connection/channel/direct/AbstractDirectChannel.java, src/main/java/net/schmizz/sshj/connection/channel/direct/SessionChannel.java, src/main/java/net/schmizz/sshj/sftp/RemoteDirectory.java, src/main/java/net/schmizz/sshj/sftp/SFTPEngine.java, src/main/java/net/schmizz/sshj/xfer/scp/SCPEngine.java, src/test/java/com/hierynomus/sshj/test/util/FileUtil.java, src/test/java/net/schmizz/sshj/util/BufferTest.java, src/test/java/net/schmizz/sshj/util/gss/BogusGSSContext.java
Here's the fix as promised in Issue #277. Feel free to make changes.
=> Added charset support, centralized UTF-8 usage

build.gradle, src/main/java/net/schmizz/sshj/userauth/password/ConsolePasswordFinder.java, src/test/java/net/schmizz/sshj/userauth/password/TestConsolePasswordFinder.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
* I didn't find a `PasswordFinder` to prompt a user for their password,
so this adds that implementation
=> Add ConsolePasswordFinder to read from Console

src/main/java/com/hierynomus/sshj/signature/SignatureEdDSA.java, src/main/java/net/schmizz/sshj/signature/AbstractSignature.java, src/main/java/net/schmizz/sshj/signature/Signature.java, src/main/java/net/schmizz/sshj/transport/kex/AbstractDHG.java, src/main/java/net/schmizz/sshj/transport/kex/AbstractDHGex.java, src/main/java/net/schmizz/sshj/userauth/method/KeyedAuthMethod.java, src/test/java/net/schmizz/sshj/signature/VerificationTest.java
Initially (hah), the signature API was slightly unclear in that if you called `Signature#initialize(PublicKey, PrivateKey)` with non-null `publicKey` and `privateKey`, the underlying `Signature` would only be initialized for signing, and not verification.
=> Disambiguated signature initialization

src/main/java/net/schmizz/sshj/common/SecurityUtils.java
On my servers, BouncyCastle was failing to register because the `java.security` file listed DSA as a disabled algorithm (no matter the keysize). It wasn't clear from the logs that the problem was that the BouncyCastle jar was signed using DSA.
```
INFO [net.schmizz.sshj.common.SecurityUtils] Registration of Security Provider 'org.bouncycastle.jce.provider.BouncyCastleProvider' unexpectedly failed
INFO [net.schmizz.sshj.common.SecurityUtils] BouncyCastle not registered, using the default JCE provider
```
By logging the root cause, it's much easier to identify and fix the problem.
```
INFO [net.schmizz.sshj.common.SecurityUtils] Registration of Security Provider 'org.bouncycastle.jce.provider.BouncyCastleProvider' unexpectedly failed
java.lang.SecurityException: JCE cannot authenticate the …
```
=> Log security provider registration failures

src/main/java/net/schmizz/sshj/AndroidConfig.java, src/main/java/net/schmizz/sshj/DefaultConfig.java, src/main/java/net/schmizz/sshj/common/SecurityUtils.java, src/main/java/net/schmizz/sshj/userauth/keyprovider/PKCS8KeyFile.java
As mentioned in https://github.com/hierynomus/sshj/issues/308#issuecomment-288636517, PCKS8KeyFile had a hard dependency on BouncyCastle as JCE provider.
In combination with SpongyCastle on Android an the updated AndroidConfig, this leads to exceptions when running on Android and using publickey auth (excerpt from my Android app):
```
21:18:17.060 [AsyncTask #5] ERROR net.schmizz.concurrent.Promise - <<authenticated>> woke to: net.schmizz.sshj.userauth.UserAuthException: Problem getting private key from PKCS8KeyFile{resource=[PrivateKeyFileResource] /storage/emulated/0/ssh/ID_Andromeda}
21:18:17.067 [AsyncTask #5] INFO  d.e.rpicheck.ssh.impl.RaspiQuery - Authentification failed.
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
at …
```
=> Android Compability, again ;-) 

src/main/java/net/schmizz/sshj/transport/verification/OpenSSHKnownHosts.java
Reasons:
1) SimpleEntry (was replaced to HostEntry) class had public constructor
2) HostEntry class can be used outside of sshj library to add entries to .known_hosts file (i.e. for implementation of interactive HostKeyVerifier)
=> HostEntry constructor must be public

src/main/java/net/schmizz/sshj/common/Buffer.java, src/test/java/net/schmizz/sshj/common/BufferTest.java
While working with openssh signed certificate of type **ssh-rsa-cert-v01@openssh.com** , i encountered the following exception \:
```
java.lang.ArrayIndexOutOfBoundsException: 514
at net.schmizz.sshj.common.Buffer.putUInt64Unchecked(Buffer.java:375)
at net.schmizz.sshj.common.Buffer.putUInt64(Buffer.java:362)
at net.schmizz.sshj.common.KeyType$CertUtils.writePubKeyContentsIntoBuffer(KeyType.java:340)
at net.schmizz.sshj.common.KeyType$7.writePubKeyContentsIntoBuffer(KeyType.java:217)
at net.schmizz.sshj.common.KeyType.putPubKeyIntoBuffer(KeyType.java:281)
at net.schmizz.sshj.common.Buffer.putPublicKey(Buffer.java:477)
at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:51)
at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:62)
at …
```
=> add Buffer capacity check for type UInt64

src/main/java/net/schmizz/sshj/transport/KeyExchanger.java, src/main/java/net/schmizz/sshj/transport/verification/FingerprintVerifier.java, src/main/java/net/schmizz/sshj/transport/verification/OpenSSHKnownHosts.java, src/test/groovy/com/hierynomus/sshj/transport/verification/OpenSSHKnownHostsSpec.groovy, src/test/groovy/net/schmizz/sshj/transport/verification/FingerprintVerifierSpec.groovy
In the `KeyExchanger` class there is the following error logging:
`
log.error("Disconnecting because none of the configured Host key verifiers ({}) could verify '{}' host key with fingerprint {} for {}:{}",
hostVerifiers,
KeyType.fromKey(key),
SecurityUtils.getFingerprint(key),
transport.getRemoteHost(),
transport.getRemotePort());
`
However the `hostVerifiers`'s elements do not properly override the `toString()` method.
It would be nice to see actual contents of this array for debug purposes.
=> Improving logging for KeyExchanger

src/main/java/net/schmizz/sshj/connection/channel/AbstractChannel.java, src/main/java/net/schmizz/sshj/connection/channel/Window.java
When the remove window size is expanded, a condition is waited on until
the remote server acknowledges and completes the action. If the server
does not respond, e.g. due to a connectivity issue, then this blocks the
client indefinitely. Instead the client waits up to the connection's
timeout (500 min default) and fails. This allows users to set a reasonable
timeout, fail their operations, and retry accordingly.
@hierynomus do you want this unit tested? If so, can you hint to how using your fixtures?
=> Add lock timeout for remote action (fixes #466)

src/main/java/net/schmizz/sshj/connection/ConnectionImpl.java
RFC 4254 section 4 states that either side of the connection
may send global requests at any time and that the receiver
MUST respond appropriately.
This PR replaces the default logic of responding with 'UNIMPLEMENTED'
with the correct 'MSG_REQUEST_FAILURE' if 'wantReply' is set.
=> Handle server initiated global requests

src/main/java/net/schmizz/sshj/connection/channel/SocketStreamCopyMonitor.java, src/test/java/net/schmizz/sshj/connection/channel/SocketStreamCopyMonitorTest.java
@hierynomus I'm not sure if I understand the responsibility of SocketStreamCopyMonitor correctly. It seems it should wait for all streams to finish, but it's not (See #317 ).
=> Fix local port forwarding disconnecting issue

src/main/java/net/schmizz/sshj/common/Buffer.java, src/main/java/net/schmizz/sshj/common/ByteArrayUtils.java, src/test/java/com/hierynomus/sshj/userauth/method/AuthKeyboardInteractiveTest.java, src/test/java/com/hierynomus/sshj/userauth/method/AuthPasswordTest.java
According to [RFC 4252](https://tools.ietf.org/html/rfc4252#section-8) and [RFC 4256](https://tools.ietf.org/html/rfc4256#section-3.4), passwords should be encoded in UTF-8. Currently all `char`s in passwords are being rounded to `byte` with loosing precision, so any attempt to authenticate with a non-ASCII symbol in a password fails.
=> Fix non-ASCII passwords

src/main/java/net/schmizz/sshj/common/StreamCopier.java, src/test/java/net/schmizz/sshj/common/StreamCopierTest.java
Relative time should be measured by System.nanoTime instead of System.currentTimeMillis
currentTimeMillis might return incorrect results during time adjustments, for example day light savings adjustments.
=> Use nano time instead of current time millis.

src/main/java/com/hierynomus/sshj/common/KeyDecryptionFailedException.java, src/main/java/com/hierynomus/sshj/userauth/keyprovider/OpenSSHKeyV1KeyFile.java, src/main/java/net/schmizz/sshj/userauth/keyprovider/PKCS8KeyFile.java, src/test/java/net/schmizz/sshj/keyprovider/OpenSSHKeyFileTest.java
While PKCS8KeyFile uses PasswordFinder's shouldRetry to determine
whether it should call reqPassword again if decryption of they key file
fails, OpenSSHKeyV1KeyFile simply gives up and throws an exception.
With this commit, retry logic similar to that of PKCS8KeyFile is added
to OpenSSHKeyV1KeyFile. The PasswordFinder's reqPassword is called
again if the validation of the "checkint" fails, which indicates an
incorrect passphrase.
=> Add pwdf retry logic to OpenSSHKeyV1KeyFile

src/main/java/com/hierynomus/sshj/common/KeyAlgorithm.java, src/main/java/com/hierynomus/sshj/userauth/keyprovider/OpenSSHKeyV1KeyFile.java, src/main/java/net/schmizz/sshj/common/ECDSAVariationsAdapter.java, src/main/java/net/schmizz/sshj/common/KeyType.java, src/main/java/net/schmizz/sshj/transport/kex/Curve25519DH.java, src/main/java/net/schmizz/sshj/transport/kex/ECDH.java, src/main/java/net/schmizz/sshj/transport/verification/OpenSSHKnownHosts.java, src/main/java/net/schmizz/sshj/userauth/keyprovider/PKCS5KeyFile.java, src/main/java/net/schmizz/sshj/userauth/keyprovider/PuTTYKeyFile.java, src/test/groovy/net/schmizz/sshj/signature/SignatureDSASpec.groovy, src/test/java/net/schmizz/sshj/signature/SignatureDSATest.java, src/test/java/net/schmizz/sshj/util/KeyUtil.java
Android Keystore private keys do not implement PrivateKey since the
raw key material is not available to applications.
With this commit, sshj's KeyType correctly detects the algorithm
associated with Android Keystore keys, which makes them usable for SSH
authentication.
=> Make KeyType compatible with Android Keystore

src/main/java/net/schmizz/sshj/sftp/SFTPEngine.java
=> Allow to query for server extensions available.

src/main/java/net/schmizz/sshj/userauth/keyprovider/PKCS8KeyFile.java
If no provider is set in the `SecurityUtils`, no named provider should be set for the `JcaPEMKeyConverter` as this would cause a `missing provider` exception. This currently breaks `PKCS8KeyFile` if `SecurityUtils.setSecurityProvider(null)` and `SecurityUtils.setRegisterBouncyCastle(false)` is used.
=> Don't specify JcaPEM providers as null

src/main/java/net/schmizz/sshj/DefaultConfig.java
The current implementation relies on `VMPCRandomGenerator` for random number generation if BouncyCastle is registered, otherwise it falls back to `SecureRandom`. Nowadays, `SecureRandom` should always be the best available option, whereas `VMPCRandomGenerator` [has known weaknesses](https://books.google.de/books?id=niO6BQAAQBAJ&pg=PA140&lpg=PA140&dq=vmpc+prng&source=bl&ots=QAdZJOT607&sig=ACfU3U0Edqlpm08iRZJLxeWGQNwNQz7WsQ&hl=en&sa=X&ved=2ahUKEwjd2Zyr9pfqAhXWMMAKHT70AioQ6AEwDnoECAoQAQ#v=onepage&q=vmpc%20prng&f=false).
=> Always use JCERandom as the default RNG

src/main/java/com/hierynomus/sshj/userauth/keyprovider/OpenSSHKeyV1KeyFile.java, src/test/java/net/schmizz/sshj/keyprovider/OpenSSHKeyFileTest.java
Mimics the behavior of `decrypt()` in `PKCS5KeyFile.java`.
=> Clear passphrase bytes after use

src/main/java/net/schmizz/sshj/connection/channel/direct/DirectConnection.java
This pullrequest fixed #555. Since openssh 8.0 the serve will check that the originator port has a valid port. 65536 is not a valid port as per definition. So we just fallback and use the last possible port which is 65535.
[Link to rfc](https://tools.ietf.org/html/rfc7605#:~:text=Current%20Port%20Number%20Use,-RFC%206335%20indicates&text=The%20port%20numbers%20from%201024,port%20numbers%20are%20not%20assigned.)
=> Fix localport for openssh >= 8.0

src/main/java/net/schmizz/sshj/signature/SignatureECDSA.java
SignatureECDSA.encode() does not correctly handle signatures longer
than 128 bytes, which affects signatures using the nistp521 curve.
This commits fixes the issue by replacing the ad-hoc ASN.1 DER
parsing with a use of ASN1InputStream.
=> Fix transport encoding of nistp521 signatures

src/main/java/net/schmizz/sshj/userauth/keyprovider/PKCS5KeyFile.java
In some cases, current code will leak parts or even the whole ssh key if it's slightly malformed.
One example of that malformation will be a key, where all newlines are replaced by other character, thus turning a multiline key to a single big string.
Then that whole line will be leaked to exception message. Thus I suggest to completely remove any parts of key from getting into the exception.
=> Avoid key leakage.

src/main/java/net/schmizz/sshj/common/SecurityUtils.java, src/main/java/net/schmizz/sshj/transport/kex/ECDHNistP.java
* Instead of only counting BouncyCastle as being registered if it is set as the explicit security provider used by SSHJ, count it as
registered if it is available as a provider. This improves Android compatibility, which requires not specifying an explicit provider. This is meant to address https://github.com/hierynomus/sshj/pull/586#issuecomment-704006627 
@oakkitten Could you verify that this fixes the issue with ECDSA host keys?
* The ECNamedCurveGenParameterSpec is a BC-specific workaround for missing curve tables in Java 1.4 and earlier. For the sake of Android compatibility, where Conscrypt can't deal with this custom spec class, replace it with the standard ECGenParameterSpec and update the curve names to the standard identifiers.
=> Improve Android compatibility

src/main/java/com/hierynomus/sshj/transport/IdentificationStringParser.java
Currently, sshj logs a warning when a a server identifies itself with a string that is not terminated as expected with CR LF but only LF.
As a user of ssh, I may have no control over the server I am connecting to and can do nothing to remediate the underlying issue. At the same time, sshj handles this situation very gracefully. Therefore, I'd consider the log level _warning_ as too high.
To ensure helpful logging of the library, I suggest to reduce the log level from _warn_ to _info_.
=> reduced log level for lenient handling of missing CR

build-publishing.gradle, build.gradle
[Bouncy Castle 1.65 and 1.66 are vulnerable to CVE-2020-28052](https://github.com/bcgit/bc-java/wiki/CVE-2020-28052).
I think this isn't relevant for SSHJ directly but for people getting Bouncy Castle transitively via SSHJ.
I couldn't test this PR, the `:jar` task fails on my machine when copying `MANIFEST.MF`.
=> Bump bouncycastle version

src/main/java/net/schmizz/sshj/xfer/scp/SCPUploadClient.java
**Problem:**
When trying to SCP a file to a remote machine, where the file exists (overwrite) and the user you're using for SCP is not the owner of the file, you get error "set mode: Operation not permitted", whenever -p switch is specified.
**Solution:**
Added a boolean variable to toggle usage of -p switch when using SCPUploadClient.copy()
Since it's an extend, the default behavior is unchanged, omitting -p is optional and needs to be explicitly specified.
=> Minor improvement for SCP preserve flag:

README.adoc, src/itest/docker-image/test-container/sshd_config, src/itest/groovy/com/hierynomus/sshj/transport/cipher/CipherSpec.groovy, src/main/java/com/hierynomus/sshj/transport/cipher/ChachaPolyCipher.java, src/main/java/com/hierynomus/sshj/transport/cipher/ChachaPolyCiphers.java, src/main/java/net/schmizz/sshj/transport/Decoder.java, src/main/java/net/schmizz/sshj/transport/Encoder.java, src/main/java/net/schmizz/sshj/transport/cipher/BaseCipher.java, src/main/java/net/schmizz/sshj/transport/cipher/Cipher.java, src/main/java/net/schmizz/sshj/transport/cipher/NoneCipher.java, src/test/java/com/hierynomus/sshj/transport/ChachaPolyCipherTest.java
=> Support cipher chacha20-poly1305@openssh.com

src/main/java/net/schmizz/sshj/common/Buffer.java, src/main/java/net/schmizz/sshj/connection/ConnectionImpl.java, src/main/java/net/schmizz/sshj/connection/channel/AbstractChannel.java, src/main/java/net/schmizz/sshj/connection/channel/ChannelInputStream.java, src/main/java/net/schmizz/sshj/connection/channel/ChannelOutputStream.java, src/test/java/net/schmizz/sshj/common/BufferTest.java
this is required to support channel ids greater than Integer.MAX_VALUE
fixes hierynomus/sshj#690
=> Support writing unsigned integers to buffer

README.adoc
This pull request updates several status badges in the project README to reflect current locations.
The Build badge references GitHub Actions in place of Travis CI, and the Codacy Grade link reflects the current Codacy project location. [Bintray](https://status.bintray.com/) is no longer operational, so this pull request removes the Download badge and link.
=> Update Build and Code Quality badges

build.gradle, src/main/java/com/hierynomus/sshj/userauth/keyprovider/OpenSSHKeyV1KeyFile.java, src/main/java/com/hierynomus/sshj/userauth/keyprovider/bcrypt/BCrypt.java, src/test/java/com/hierynomus/sshj/userauth/keyprovider/bcrypt/BCryptTest.java
As described in issue #706, the class name of `org.mindrot.jbcrypt.BCrypt` conflicts with a class of the same name in the original `org.mindrot:jbcrypt` library. With the SSHJ BCrypt class implementing the additional `pbkdf()` method, the two classes are not interchangeable. Relocating the `BCrypt` class under the `com.hierynomus.sshj` package structure avoids class path conflicts in applications that have dependencies on both SSHJ and JBcrypt libraries. Additional changes include renaming and updating the `BCryptTest` class to use standard JUnit Test annotations.
=> Move BCrypt class to avoid conflict with org.mindrot:jbcrypt

src/main/java/net/schmizz/sshj/userauth/keyprovider/PuTTYKeyFile.java, src/test/java/net/schmizz/sshj/keyprovider/PuTTYKeyFileTest.java
Hi! 
With the latest PuTTY, the header line has changed to "PuTTY-User-Key-File-3".
This trivial patch will parse both old and new PuTTY key files correctly.
=> Support v3 PuTTY keys

build.gradle
This pull request upgrades [SLF4J](http://www.slf4j.org/news.html) from 1.7.30 to 1.7.32, and upgrades [Logback](http://logback.qos.ch/news.html) from 1.2.3 to 1.2.6.
These upgrades include several minor bug fixes in both libraries.
=> Upgrade SLF4J to 1.7.32 and Logback to 1.2.6

src/main/java/net/schmizz/sshj/transport/KeyExchanger.java, src/main/java/net/schmizz/sshj/transport/Proposal.java, src/main/java/net/schmizz/sshj/transport/verification/FingerprintVerifier.java, src/main/java/net/schmizz/sshj/transport/verification/HostKeyVerifier.java, src/main/java/net/schmizz/sshj/transport/verification/OpenSSHKnownHosts.java, src/main/java/net/schmizz/sshj/transport/verification/PromiscuousVerifier.java
(#642, #635... 10? issues)
Try to find the Algorithm that was used when a known_host
entry was created and make that the first choice for the
current connection attempt.
If the current connection algorithm matches the
algorithm used when the known_host entry was created
we can get a fair verification.
=> Prefer known algorithm for known host

src/main/java/com/hierynomus/sshj/userauth/keyprovider/OpenSSHKeyV1KeyFile.java, src/test/java/net/schmizz/sshj/keyprovider/OpenSSHKeyFileTest.java
Key parsing in `OpenSSHKeyV1KeyFile` currently parses RSA Private Keys and returns an `RSAPrivateKeySpec` containing the modulus and private exponent. As a result of this approached, the BouncyCastle implementation of `RSAPrivateKey.getEncoded()` returns `0` for all other fields when serializing the the key to an ASN.1 encoded PrivateKeyInfo byte array.  This creates problems writing RSA Private Keys to PKCS8 PEM files as described in issue #705.
This pull request updates RSA Private Key parsing in `OpenSSHKeyV1KeyFile` to read and use the available elements of the RSA Private Key. Following [RFC 8017 Section 3.2](https://datatracker.ietf.org/doc/html/rfc8017#section-3.2), the updated approach calculates the Prime Exponent P and Prime Exponent Q values, then returns an …
=> Update OpenSSH Key V1 parsing using CRT information for RSA Private Keys

src/main/java/net/schmizz/sshj/userauth/keyprovider/PuTTYKeyFile.java, src/test/java/net/schmizz/sshj/keyprovider/PuTTYKeyFileTest.java
As mentioned in https://github.com/hierynomus/sshj/pull/716 the current Puttyv3 support is limited to unencrypted key files as the new file format uses Argon based key derivation functions . This PR adds checks so that we do not try to decrypt a key we can never decrypt successfully because of the missing Argon implementation.
Instead a describing exception is thrown so it is clear that the password was not the problem. 
A unit test for an encrypted RSA putty v3 key has been added.
Additionally I made some small optimizations on the putty key loading code.
=> only process supported Putty v3 keys + minor optimizations

build.gradle, src/itest/groovy/com/hierynomus/sshj/RsaShaKeySignatureTest.groovy, src/itest/groovy/com/hierynomus/sshj/SshServerWaitStrategy.java, src/itest/groovy/com/hierynomus/sshj/SshdContainer.java, src/main/java/com/hierynomus/sshj/key/KeyAlgorithms.java, src/main/java/net/schmizz/sshj/ConfigImpl.java, src/main/java/net/schmizz/sshj/transport/KeyExchanger.java, src/main/java/net/schmizz/sshj/transport/NegotiatedAlgorithms.java, src/main/java/net/schmizz/sshj/transport/Proposal.java, src/main/java/net/schmizz/sshj/transport/TransportImpl.java, src/main/java/net/schmizz/sshj/userauth/method/KeyedAuthMethod.java, src/test/groovy/com/hierynomus/sshj/userauth/keyprovider/FileKeyProviderSpec.groovy, src/test/groovy/net/schmizz/sshj/ConfigImplSpec.groovy
Previously, there was a heuristic that was choosing rsa-sha2-512 after receiving a host key of type RSA. It didn't work well when a server doesn't have an RSA host key.
OpenSSH 8.8 introduced a breaking change: it removed ssh-rsa from the default list of supported public key signature algorithms. SSHJ was unable to connect to OpenSSH 8.8 server if the server has an EcDSA or Ed25519 host key.
Current behaviour behaves the same as OpenSSH 8.8 client does. SSHJ doesn't try to determine rsa-sha2-* support on the fly. Instead, it looks only on `Config.getKeyAlgorithms()`, which may or may not contain ssh-rsa and rsa-sha2-* in any order.
Sorry, this commit mostly reverts changes from #607.
Apparently, I tried to find a way to determine if the server supports some key algorithm signature. I …
=> Lean on Config.keyAlgorithms choosing between rsa-sha2-* and ssh-rsa

build.gradle, src/main/java/net/schmizz/sshj/connection/channel/forwarded/RemotePortForwarder.java, src/test/java/com/hierynomus/sshj/connection/channel/forwarded/RemotePortForwarderTest.java, src/test/java/com/hierynomus/sshj/test/SshFixture.java, src/test/java/com/hierynomus/sshj/transport/kex/KeyExchangeTest.java, src/test/java/com/hierynomus/sshj/userauth/method/AuthKeyboardInteractiveTest.java, src/test/java/com/hierynomus/sshj/userauth/method/AuthPasswordTest.java
This pull requests upgrades Bouncy Castle and multiple test dependencies to more recent versions.
- Upgraded Bouncy Castle from 1.69 to 1.70
- Upgraded Apache SSHD from 2.1.0 to 2.8.0
- Upgraded JUnit from 4.12 to 4.13.2
- Upgraded Mockito from 2.28.2 to 4.2.0
- Upgraded Logback from 1.2.6 to 1.2.9
- Upgraded Apache HTTP Client from 4.5.9 to 4.5.14
Changes in recent versions of Apache SSHD required several adjustments to test classes and provided the opportunity to streamline some of the fixture configuration.
=> Upgrade Bouncy Castle to 1.70 and upgrade test dependencies

src/main/java/net/schmizz/sshj/sftp/SFTPEngine.java
Pull request #652 introduced support for SFTP rename flags, which was released in SSHJ 0.32.0. The `SFTPEngine.rename()` method includes the rename flag mask without checking the SFTP operative version, causing communication issues described in #750 and #751.
The [SFTP Version 5 Section 6.5](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-05#section-6.5) specification added support for rename flags, but previous versions such as [SFTP Version 3](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-03#section-6.5) do not support rename flags.
This pull request changes the behavior and avoids appending the rename flag mask to the SFTP request packet for operative versions less than 5.
=> Avoid setting SFTP rename flags below version 5

src/main/java/net/schmizz/keepalive/KeepAlive.java, src/main/java/net/schmizz/sshj/SSHClient.java, src/test/java/com/hierynomus/sshj/keepalive/KeepAliveThreadTerminationTest.java
The current `KeepAlive.setKeepAliveInterval()` method starts the Thread when invoked with an interval greater than zero. This behavior starts the KeepAlive Thread prior to establishing a connection, depending on when the caller invokes `setKeepAliveInterval()`. 
Neither the `ConnectionImpl` class nor the `SSHClient` class interrupt the KeepAlive Thread, resulting in continued looping inside of `KeepAlive.run()` even after disconnecting and closing `SSHClient` as described in issue #506.
This pull request changes the behavior of `KeepAlive.setKeepAliveInterval()` to avoid starting the Thread.  The `SSHClient.onConnect()` method checks whether the KeepAlive Thread is enabled and then calls `start()` to avoid unnecessary execution prior to a successful connection. The …
=> Update SSHClient to interrupt KeepAlive Thread when disconnecting

src/main/java/com/hierynomus/sshj/common/RemoteAddressProvider.java, src/main/java/com/hierynomus/sshj/common/ThreadNameProvider.java, src/main/java/net/schmizz/keepalive/KeepAliveRunner.java, src/main/java/net/schmizz/sshj/SSHClient.java, src/main/java/net/schmizz/sshj/connection/channel/direct/SessionFactory.java, src/main/java/net/schmizz/sshj/sftp/PacketReader.java, src/main/java/net/schmizz/sshj/sftp/SFTPEngine.java, src/main/java/net/schmizz/sshj/transport/Reader.java, src/main/java/net/schmizz/sshj/transport/Transport.java, src/main/java/net/schmizz/sshj/transport/TransportImpl.java
This pull requests adds standard Thread names for the Transport `Reader`, the SFTP `PacketReader`, and the Connection `KeepAlive` Threads.  The implementation includes a `ThreadNameProvider` class to set the Thread name prefixed with `sshj` followed by the simple class name and the remote socket address.  The following provides an example name for the Transport `Reader` Thread:
```
sshj-Reader-localhost/127.0.0.1:22
```
This approach to thread naming provides association with SSHJ, identification of the Thread implementation, and the ability to distinguish between connections to different endpoints. These changes address the troubleshooting challenges described in issue #738.
=> Add Thread naming based on remote socket address

src/main/java/net/schmizz/sshj/transport/Transport.java, src/main/java/net/schmizz/sshj/transport/TransportImpl.java, src/main/java/net/schmizz/sshj/userauth/method/KeyedAuthMethod.java
=> Try all public key algorithms available for a specific key type in SSH_MSG_USERAUTH_REQUEST

src/main/java/net/schmizz/sshj/sftp/RemoteFile.java, src/test/java/com/hierynomus/sshj/sftp/RemoteFileTest.java
If an instance of ReadAheadRemoteFileInputStream before this change is wrapped into a BufferedInputStream with a big buffer, the SSH client requests big packets from the server. It turned out that if the server had sent a response smaller than requested, the client wouldn't have adjusted to decreased window size, and would have read the file incorrectly.
This change detects cases when the server is not able to fulfil client's requests. Since this change, the client adjusts the maximum request length, sends new read-ahead requests, and starts to ignore all read-ahead requests sent earlier.
Just specifying some allegedly small constant buffer size wouldn't have helped in all possible cases. There is no way to explicitly get the maximum request length inside a client. All that limits differ …
=> Fix ReadAheadRemoteFileInputStream not reading the whole file if a buffer is too big

src/main/java/com/hierynomus/sshj/userauth/keyprovider/OpenSSHKeyV1KeyFile.java, src/test/java/net/schmizz/sshj/keyprovider/OpenSSHKeyFileTest.java
There is a contract that `FileKeyProvider.readKey` throws an IOException if something goes wrong. Throwing an NPE is not expected by API users. Also, it is much more difficult to find out if the NPE is thrown due to a broken key file, or due to an internal bug.
=> Throw IOE instead of NPE if OpenSSHKeyV1KeyFile reads an empty file

src/main/java/net/schmizz/sshj/sftp/RemoteFile.java
Due to a bug in logic introduced by #769, RemoteFile.ReadAheadRemoteFileInputStream started to send new read ahead requests for file parts that had already been requested.
Every call to read() asked the server to send parts of the file from the point which is already downloaded. Instead, it should have asked to send parts after the last requested part. This commit adds exactly this logic.
The bug didn't cause content corruption. It only affected performance, both on servers and on clients.
=> Fix #777: Don't request excessive read-ahead packets in RemoteFile

build.gradle, src/main/java/net/schmizz/sshj/sftp/RemoteFile.java, src/main/java/net/schmizz/sshj/sftp/SFTPClient.java, src/main/java/net/schmizz/sshj/sftp/SFTPFileTransfer.java, src/main/java/net/schmizz/sshj/xfer/FileSystemFile.java, src/main/java/net/schmizz/sshj/xfer/FileTransfer.java, src/main/java/net/schmizz/sshj/xfer/LocalDestFile.java, src/main/java/net/schmizz/sshj/xfer/scp/SCPFileTransfer.java, src/test/java/com/hierynomus/sshj/test/util/FileUtil.java, src/test/java/net/schmizz/sshj/sftp/SFTPFileTransferTest.java, src/test/resources/files/test_file_full.txt, src/test/resources/files/test_file_partial.txt
Internally SFTPFileTransfer has a few sanity checks to fall back to full replacement even if the resume flag is set.
SCP file transfers have not been changed to support this at this time.
=> Added SFTP file transfer resume support on both PUT and GET. 

examples/pom.xml, examples/src/main/java/net/schmizz/sshj/examples/KeepAlive.java, examples/src/main/java/net/schmizz/sshj/examples/RemotePF.java, src/main/java/net/schmizz/keepalive/KeepAlive.java
As requested in issue #784, this pull request updates the `KeepAlive` example class to set the KeepAlive interval prior to connecting, following the behavior adjustments introduced in SSHJ 0.33.0. The `RemotePF` example follows the same approach for the Heartbeat setting, and removes the call to `Transport.setHeartbeatInterval()`, which is no longer defined.
=> Update KeepAlive and RemotePF examples

src/main/java/net/schmizz/concurrent/Promise.java, src/main/java/net/schmizz/keepalive/KeepAlive.java, src/main/java/net/schmizz/sshj/connection/channel/ChannelInputStream.java, src/main/java/net/schmizz/sshj/connection/channel/Window.java
=> restore the interrupt flag whenever we catch InterruptedException

src/main/java/com/hierynomus/sshj/common/ThreadNameProvider.java, src/main/java/net/schmizz/sshj/SSHClient.java, src/main/java/net/schmizz/sshj/transport/Transport.java, src/main/java/net/schmizz/sshj/transport/TransportImpl.java, src/test/java/com/hierynomus/sshj/keepalive/KeepAliveThreadTerminationTest.java
This pull request addresses SSH_MSG_UNIMPLEMENTED errors during key exchange described in issue #810.
Changes include adding `isKeyExchangeRequired()` to the `Transport` interface, with an implementation in `TransportImpl` that checks the status of Key Exchange completion and processing.
Checking `KeyExchanger.isKexDone()` indicates that at least one key exchange has not been completed, and checking `KeyExchanger.isKexOngoing()` indicates that a key exchange is not in progress.  Checking `Transport.isKeyExchangeRequired()` in `SSHClient.onConnect()` avoids sending an additional `SSH_MSG_KEXINIT` packet when a key exchange is already in progress or completed.
Additional changes include adding a started timestamp when setting a thread name in `ThreadNameProvider`. The started timestamp …
=> Add Transport.isKeyExchangeRequired() to avoid unnecessary KEXINIT

src/main/java/net/schmizz/sshj/userauth/method/PasswordResponseProvider.java, src/test/java/com/hierynomus/sshj/userauth/method/PasswordResponseProviderTest.java
FreeBSD "keyboard-interactive" prompt is "Password for user@host:"
=> Support SSHClient.authPassword on FreeBSD

src/main/java/net/schmizz/concurrent/Promise.java
A minor improvement to include the actual timeout value into the exception message. 
This can get handy in complex scenarios where it is not obvious what timeout is configured for the command that had failed.
=> TimeoutException message improved

README.adoc, build-publishing.gradle, build.gradle, src/main/java/net/schmizz/sshj/transport/compression/ZlibCompression.java
The JRE already contains a gzip implementation in `java.util.zip.*`, so we should be able to use that rather than relying on the external jCraft library.
=> Remove jzlib dependency

src/main/java/net/schmizz/sshj/SSHClient.java
Avoids casting requirement:
```
StatefulSFTPClient statefulSftpClient = (StatefulSFTPClient) sshClient.newStatefulSFTPClient();
```
=> Have newStatefulSFTPClient return StatefulSFTPClient

.github/workflows/gradle.yml, README.adoc, build.gradle, src/itest/groovy/com/hierynomus/sshj/RsaShaKeySignatureTest.groovy, src/test/java/com/hierynomus/sshj/connection/channel/forwarded/LocalPortForwarderTest.java, src/test/java/com/hierynomus/sshj/connection/channel/forwarded/RemotePortForwarderTest.java
This pull requests changes the Java compiler release version from 7 to 8, making the Java 8 the minimum required version for using SSHJ.
Runtime dependency changes include the following updates:
- Upgraded Bouncy Castle from 1.70 to [1.75](https://bouncycastle.org/releasenotes.html#r1rv75)
- Upgraded SLF4J from 1.7.36 to [2.0.7](https://www.slf4j.org/news.html#2023-03-17%20-ReleaseOfSLF4J2.0.7)
Both of these runtime dependency upgrades require Java 8.
Test dependency changes include the following updates:
- Upgraded Logback from 1.2.11 to [1.3.8](https://logback.qos.ch/news.html#1.3.8)
- Upgraded Apache MINA SSHD from 2.8.0 to 2.10.0
- Upgraded Grizzly HTTP Server from 2.4.4 to 3.0.1
- Upgraded Testcontainers from 1.16.2 to 1.18.3
- Upgraded Spock from 1.3 to 2.0
GitHub Action changes …
=> Set Java 8 as Minimum Required Version and Upgrade Dependencies

src/itest/java/com/hierynomus/sshj/sftp/PutFileCompressedTest.java, src/main/java/net/schmizz/sshj/transport/compression/ZlibCompression.java
This PR addresses #893 and builds on top of #900, which provided a failing test.
=> Fix zlib compression

src/main/java/net/schmizz/sshj/Config.java, src/main/java/net/schmizz/sshj/ConfigImpl.java, src/main/java/net/schmizz/sshj/common/CircularBuffer.java, src/main/java/net/schmizz/sshj/connection/channel/AbstractChannel.java, src/main/java/net/schmizz/sshj/connection/channel/ChannelInputStream.java, src/main/java/net/schmizz/sshj/connection/channel/direct/SessionChannel.java, src/test/java/com/hierynomus/sshj/connection/channel/forwarded/RemotePFPerformanceTest.java, src/test/java/net/schmizz/sshj/common/CircularBufferTest.java
This PR addresses https://github.com/hierynomus/sshj/issues/658.
The `Buffer` class can grow out of control when its consumer is unable to read data quickly enough to keep up with the producer for an extended period of time. This results in an out of memory (OOM) condition during ssh port forwarding. This issue has been hit in production at Delphix many times.
When `ChannelInputStream` receives new data from its producer, it calls `Buffer.putRawBytes` which will double its internal array if there is not enough room to store data starting at its current write position `wpos`. Meanwhile, when the consumer reads data from `ChannelInputStream`, the buffer will advance its read position `rpos` to the next unread byte. If, and only if, the read position catches up with the write position, …
=> Fix for Remote port forwarding buffers can grow without limits (issue #658)

src/itest/java/com/hierynomus/sshj/SshdContainer.java, src/itest/java/com/hierynomus/sshj/transport/kex/StrictKeyExchangeTest.java, src/main/java/net/schmizz/sshj/transport/Converter.java, src/main/java/net/schmizz/sshj/transport/KeyExchanger.java, src/main/java/net/schmizz/sshj/transport/Proposal.java, src/main/java/net/schmizz/sshj/transport/TransportImpl.java, src/test/java/net/schmizz/sshj/transport/KeyExchangeRepeatTest.java
Resolves #916 
The PR implements the algorithm described in section 1.9 of https://github.com/openssh/openssh-portable/blob/master/PROTOCOL and also follows the changes implemented in the commit https://github.com/openssh/openssh-portable/commit/1edb00c58f8a6875fad6a497aa2bacf37f9e6cd5.
All tests are successful. The integration tests work both against the current container and a custom built container with OpenSSH 9.6p1. When run against the latter, the log also show that the resets of sequence numbers are happening, and working correctly as otherwise ChaCha20-Poly1305 should break.
The jsch fork of mwiede also implemented config switches to disable or enforce the strict key exchange extension. But I'm not sure whether it makes sense to maintain such flags long term when OpenSSH itself …
=> Implement OpenSSH strict key exchange extension

src/test/java/net/schmizz/sshj/transport/KeyExchangerStrictKeyExchangeTest.java, src/test/java/net/schmizz/sshj/transport/TransportImplStrictKeyExchangeTest.java
Thanks for merging #917!
I also wrote two unit tests for the `KeyExchanger` and the `Transport`, respectively. They cover some corner cases and in particular aborts that are an import part of the strict key exchange to address the CVE. However, they are a bit mock and reflection heavy, so they might show brittleness in the future.
=> Add unit tests of strict key exchange extension

src/main/java/net/schmizz/sshj/transport/verification/OpenSSHKnownHosts.java, src/test/java/com/hierynomus/sshj/transport/verification/OpenSSHKnownHostsTest.java
The previous Base64 implementation threw IOExceptions in some places that are now IllegalArgumentExecptions. Both are now caught and logged. OpenSSH ignores this, too.
=> known_hosts parsing does not ignore malformed base64 strings since 0.36

src/main/java/net/schmizz/sshj/SocketClient.java, src/test/java/net/schmizz/sshj/ConnectedSocketTest.java
The client should be able to accept sockets that have been already connected to a remote server.
=> connected sockets can be passed to the library

build.gradle
Bouncy Caste version before 1.78 have 
CVE-2024-29857 - Importing an EC certificate with specially crafted F2m parameters can cause high CPU usage during parameter evaluation.
Is sshj impacted by this vulnerability?
=> Update bouncyCastle to 1.78 to mitigate CVE-2024-29857

.github/workflows/gradle.yml, .github/workflows/release.yml, build.gradle
This pull request upgrades the following dependencies:
- Upgraded Bouncy Castle from 1.78 to [1.78.1](https://www.bouncycastle.org/releasenotes.html#r1rv78d1)
- Upgraded SLF4J from 2.0.7 to [2.0.13](https://www.slf4j.org/news.html#2.0.13)
- Upgraded SSHD from 2.10.0 to [2.12.1](https://mina.apache.org/sshd-project/download_2.12.1.html)
- Upgraded Logback from 1.3.8 to [1.3.14](https://logback.qos.ch/news.html#1.3.14)
- Upgraded Testcontainers from 1.18.3 to [1.19.8](https://github.com/testcontainers/testcontainers-java/releases/tag/1.19.8)
- Upgraded setup-java action to version [4](https://github.com/actions/setup-java/releases/tag/v4.2.1)
- Upgraded checkout action to version [4](https://github.com/actions/checkout/releases/tag/v4.1.5)
=> Upgrade Bouncy Castle and other dependencies

src/main/java/net/schmizz/sshj/xfer/scp/SCPDownloadClient.java
Allows the same customization of the  commandline as the scp upload.
=> Allow custom scp download command line

src/main/java/net/schmizz/sshj/transport/kex/Curve25519DH.java, src/test/java/net/schmizz/sshj/transport/kex/Curve25519DHTest.java
This pull request improves public key handling for Curve25519 key agreement when running on Java 11 without the Bouncy Castle Security Provider registered.
The Bouncy Castle Security Provider supports `X25519` and returns the encoded public key with a length of `44`. Java 17 and 21 also return encoded public keys of the same length. The Java 11 implementation of `X25519` returns the encoded public key with a length of `46`, where the DER header contains 14 bytes instead of 12. This results in exceptions at runtime as described in #957.
Adjusting the behavior of `Curve25519DH` to calculate the DER header and algorithm identifier based on the length of the encoded public key provides a solution that works across Java versions, with or without the Bouncy Castle Provider.
Changes include unit …
=> Improve Curve25519 Public Key Handling

src/main/java/net/schmizz/sshj/connection/channel/direct/SessionChannel.java
Fixes #955 
We are getting this exception frequently, when the network to the server is poor (ie., there are a lot of dropped packets at the server, for example):
```
java.lang.NullPointerException: null
at net.schmizz.sshj.connection.channel.direct.SessionChannel.notifyError(SessionChannel.java:228) ~[sshj-0.31.0.jar:0.31.0]
at net.schmizz.sshj.common.ErrorNotifiable$Util.alertAll(ErrorNotifiable.java:35) ~[sshj-0.31.0.jar:0.31.0]
at net.schmizz.sshj.connection.ConnectionImpl.notifyError(ConnectionImpl.java:261) ~[sshj-0.31.0.jar:0.31.0]
at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:620) ~[sshj-0.31.0.jar:0.31.0]
at net.schmizz.sshj.transport.Reader.run(Reader.java:66) ~[sshj-0.31.0.jar:0.31.0]
```
I can't really see how the ```err``` variable in ```SessionChannel``` …
=> Check error stream is not null before notifying error

src/main/java/com/hierynomus/sshj/userauth/keyprovider/OpenSSHKeyV1KeyFile.java, src/main/java/net/schmizz/sshj/common/ECDSACurve.java, src/main/java/net/schmizz/sshj/common/ECDSAKeyFactory.java, src/main/java/net/schmizz/sshj/common/ECDSAVariationsAdapter.java, src/main/java/net/schmizz/sshj/userauth/keyprovider/PuTTYKeyFile.java, src/test/java/net/schmizz/sshj/keyprovider/PuTTYKeyFileTest.java
This pull request refactors construction of ECDSA public and private key objects using standard Java Cryptography Architecture classes in place of Bouncy Castle classes.
These changes address some of the concerns raised in issue #973, reducing direct references to the Bouncy Castle library. Separate work is required to address other Bouncy Castle references.
The implementation introduces a new shared `ECDSAKeyFactory` class with methods for constructing `PrivateKey` and `PublicKey` objects from source material and the associated NIST Elliptic Curve. This approach reduces duplicated code from several methods that create ECDSA key objects.
=> Refactor ECDSA Key Handling using Java Security

src/itest/java/com/hierynomus/sshj/sftp/FileWriteTest.java, src/test/java/com/hierynomus/sshj/transport/GcmCipherDecryptSshPacketTest.java, src/test/java/com/hierynomus/sshj/transport/verification/OpenSSHKnownHostsTest.java, src/test/java/net/schmizz/sshj/transport/DecoderDecryptGcmCipherSshPacketTest.java, src/test/java/net/schmizz/sshj/transport/mac/BaseMacTest.java, src/test/java/net/schmizz/sshj/transport/mac/HMACMD596Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACMD5Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA196Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA1Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA2256Test.java, src/test/java/net/schmizz/sshj/transport/mac/HMACSHA2512Test.java
This pull request removes Bouncy Castle class references from tests.
Some changes involve removing unnecessary registration of the `BouncyCastleProvider` in several tests, and replacing the Bouncy Castle `Hex.toHexString()` with Apache SSHD `BufferUtils.toHex()` in other test cases.
This relates to a broader effort described in issue #973 for reducing usage of Bouncy Castle in general.
=> Remove Bouncy Castle usage from Tests

src/main/java/net/schmizz/sshj/userauth/keyprovider/EncryptedPEMKeyReader.java, src/main/java/net/schmizz/sshj/userauth/keyprovider/PuTTYKeyFile.java, src/main/java/net/schmizz/sshj/userauth/keyprovider/PuTTYSecretKeyDerivationFunction.java, src/main/java/net/schmizz/sshj/userauth/keyprovider/V1PuTTYSecretKeyDerivationFunction.java, src/main/java/net/schmizz/sshj/userauth/keyprovider/V3PuTTYSecretKeyDerivationFunction.java, src/test/java/net/schmizz/sshj/keyprovider/PuTTYKeyFileTest.java
This pull request refactors Secret Key Derivation for PuTTY Key Files, providing clear separation for Version 3 using Argon2 from Bouncy Castle, and Version 1 using SHA-1 with standard Java Security components.
The new interface abstraction provides clearer separation of the Version 3 implementation to avoid loading Bouncy Castle classes, unless required for Version 3 handling.
Additional changes include replacing Bouncy Castle `Hex` class references with available `ByteArrayUtils` methods.
These changes maintain existing support for PuTTY Key File processing.
=> Refactor PuTTY Secret Key Derivation

build.gradle, gradle/wrapper/gradle-wrapper.properties
This PR upgrades dependencies to the latest stable versions:
- Upgrade Gradle to 8.13
- Upgrade SLF4J to 2.0.17
- Upgrade Mockito to 5.16.1
- Upgrade AssertJ to 3.27.3
- Upgrade Logback to 1.5.18
- Upgrade Testcontainers to 1.20.6
=> Upgrade dependencies

build.gradle
This pull request upgrades Apache SSHD dependencies from 2.14.0 to [2.15.0](https://mina.apache.org/sshd-project/download_2.15.0.html), incorporating several features and fixes for tests.
This pull request also upgrades the SLF4J version referenced under integration test dependencies to align with the main project version of 2.0.17.
=> Upgrade SSHD from 2.14.0 to 2.15.0

build.gradle, src/test/java/com/hierynomus/sshj/connection/channel/forwarded/LocalPortForwarderTest.java, src/test/java/com/hierynomus/sshj/connection/channel/forwarded/RemotePortForwarderTest.java, src/test/java/com/hierynomus/sshj/test/HttpServer.java
This pull request replaces the Grizzly HTTP Server dependency with the standard Java [HttpServer](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.httpserver/com/sun/net/httpserver/HttpServer.html) for port forwarding unit tests.
The Java HttpServer is part of the standard JDK since Java 1.6 and requires no external dependencies.
=> Replace Grizzly HTTP Server with Java HTTP Server
